name: Main Workflow

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push:
    name: Docker Build & Push
    uses: ./.github/workflows/run-docker-build-push.yml
    with:
      image-name: qodeboy/php-fpm-exporter
      php-fpm-exporter-version: 2.2
